version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: test_todo
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123456789 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    build: ./todo-api
    env_file: ./todo-api/.env
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - "4000"
    ports:
      - "4000:4000"
    networks:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: ./todo-web
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - app
    restart: unless-stopped

networks:
  app:

volumes:
  mysql-data:
